### ISSUE TITLE
Include / exclude filters don't work with full collections

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-next#107]
Exclude/include filters don't seem to work correct at all times. It seems to give back the wrong results most of the time.

![Image](https://github.com/BuddhaNexus/buddhanexus-frontend-next/assets/49606945/50ebe8ac-3795-486f-8613-04e7a9f9a9dc)

It also shows 0 matches while there are clearly a lot of matches

![Image](https://github.com/BuddhaNexus/buddhanexus-frontend-next/assets/49606945/29e1afbd-7d68-4084-b494-105366971c34)

**Comment by ayya-vimala** [comment]
I thought I had closed this issue some time ago ..??

**Comment by aminahbl** [comment]
> I thought I had closed this issue some time ago ..??
Still open... :grin: I'm currently trying to clear out tickets, so please close any that you don't feel are relevant any more. Thanks :pray:

> The only thing it doesn't do is update the matches in the middle column if there are 0.
It also leaves matches unavailable after applying filters. The PR does a crude reset to clear these on filter change; unfortunately, at the moment, I don't think there is enough data to persist matches that still apply.

**Comment by ayya-vimala** [comment]
This seems to work.
