### ISSUE TITLE
Long filenames in dropdown

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-next#138]
See screenshot below. The entry for Tha-Ap is two lines and both lines are half disappearing under the previous and next lines.

![Image](https://github.com/BuddhaNexus/buddhanexus-frontend-next/assets/49606945/de3d710a-36e7-46bd-80d0-0137dbe60f54)

**Comment by ayya-vimala** [comment]
I think what is needed here is a change in `category.ts` on line 25. This should be:
`label: `${categoryname}`` But I'm not entirely sure as I don't know the frontend. In any case, the `category` should not be mentioned before the `categoryname` and the dot should not be removed from the response.

**Comment by aminahbl** [comment]
Superseded by #183.

**Comment by ayya-vimala** [comment]
Moving this ticket to done column.
