### ISSUE TITLE
Download button in Table View downloads the Numbers View

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-next#145]
When I select a file in Table View with certain parameters and then click in the Settings Menu on `Download results as xmlx file` I get the Numbers View instead of the Table View.

**Comment by ayya-vimala** [comment]
Download is not working at all at present.

**Comment by aminahbl** [comment]
This is know, nothing can be done without the BE

**Comment by ayya-vimala** [comment]
It's a frontend issue. The frontend gives a GET request but is should be a POST request as outlined above. It works for me in Postman. The backend is giving back the correct data.

**Comment by aminahbl** [comment]
It hasn't been wired up on the FE because wasn't ready for it, please see the several requests made on this point in Discord.

**Comment by sebastian-nehrdich** [comment]
Just out of curiosity: doesn’t the new BN front end handle all parameter
settings in the url as well now? So why do we even need a “download” button
if it is now possible to link to table view results with precise filter
settings? I feel this feature is redundant and adds a lot of unnecessary
complexity to our server setup. I just try to understand what’s the use
case apart from perhaps looking at results during a meditation retreat
without internet? Even in that case the user might achieve that more easily
by just downloading the website in their browser or printing it to a pdf
file. We might offer a “show all results on one page “ option that bypasses
pagination to make sure the users get all results when they download it.
I just try to get rid of features that bog us down and don’t add distinct
value to the page.

**Comment by TrebuhD** [comment]
yes good point, we could make the website a PWA (!) to handle this case of needing to use it offline.

**Comment by ayya-vimala** [comment]
I think we added that xls download because Orna liked to manage results in an xls spreadsheet. It doesn't download to a pdf but to an xls file.

**Comment by sebastian-nehrdich** [comment]
Yes, that’s the background — I am happy to talk to her, just try to
understand what we want to achieve with this feature

**Comment by ayya-vimala** [comment]
The feature actually works in the backend as I spend a lot of time on revamping it in May. But there's an issue I suspect with the NGINX settings so it should be fairly easy to make it work.

**Comment by aminahbl** [comment]
It may have been crossed wires over the various development lulls, I recall trying to pick this up a couple of times, but finding something was unresolved at those points and I couldn't finish. It's possible that now some bit needs to be updated on the FE. Let's discuss at the meeting.

**Comment by ayya-vimala** [comment]
Connected to #245 
Trying to use BytesIO to download the file rather than storing it on the server and taking up space.

**Comment by ayya-vimala** [comment]
Closing this issue as we opened #184 . Care should be taken that the  `download_data=''` parameter is set to `table` or `numbers` depending on which view is requested for download.
