### ISSUE TITLE
Add logic to handle language sepcific views to view selector 

### ISSUE THREAD

**Issue by aminahbl** [BuddhaNexus/buddhanexus-frontend-next#151]

**Comment by ayya-vimala** [comment]
Can you let me know what this issue is exactly? I take it that it is for a multilingual matches view so you can decide to get f.i. just the match results for one or two languages and not all?

**Comment by aminahbl** [comment]
I think this has been done now. Only pli & chn have all views available, so numbers view should be listed for tib & skt.

**Comment by ayya-vimala** [comment]
Okay, so it is not what I thought. But as far as I can see all languages list numbers view as an option, including tibetan and sanskrit so is it simply not merged and running on BN2 yet?

**Comment by aminahbl** [comment]
Prolly not then.

**Comment by ayya-vimala** [comment]
I can't check Chinese as no data but it's probably okay. Everything else is fine.
