### ISSUE TITLE
Limit filters getting lost when switching modes

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend-next#161]
Steps to take:

1. Choose a text and open it in text-view
2. Open settings and set a limit filters to another text or two
3. Switch mode to table-view
4. You will see indeed all the matches that are for the set filter settings.
5. Look at the settings and see there are no filters visible any more; the dropdowns are empty. so I no longer know which filters I set and also I cannot undo a certain filter if I had set more than one. The view is filtered correctly but the filters are no longer visible.

I would expect the set filters to remain visible when going between modes.

**Comment by aminahbl** [comment]
Followed steps to reproduce, but the issue seems to be resolved.

**Comment by ayya-vimala** [comment]
No, it's not resolved.
The filter number seems to remain using the filters but the dropdowns in the setting don't show which filter is used.
F.i.
View before any filters are set:


![Image](https://github.com/user-attachments/assets/cae79d82-4b27-49c9-8444-de1f1e9c4a7a)

Set filter to just show MN shows that number of matches are decreased:


![Image](https://github.com/user-attachments/assets/520c337f-5001-414f-ba31-46b8b6d53cd1)

Change to text-view mode:


![Image](https://github.com/user-attachments/assets/9a4afb8f-1dae-4e4c-832c-1aa2614b29ec)


You can see that the filter is applied but you no longer know which filter it is as the dropdowns are empty. (bottom right of the screenshot)

**Comment by aminahbl** [comment]
The image steps are shown in reverse of what is given in the description

> 1. Choose a text and open it in text-view
> 2. Open settings and set a limit filters to another text or two
> 3. Switch mode to table-view

So is the actual problem from table-view to text-view?

**Comment by ayya-vimala** [comment]
It doesn't matter. text view -> table view or table view -> text view both loose the information of the filter settings.

**Comment by aminahbl** [comment]
Okay now I understand why we're reporting different things. When I first looked at this, I only tested locally. I just re-tested now  both locally and on the live v2 site: locally it works as expected, on the v2 site, I got exactly the same results as you. 

I'm cautious to start digging into this any further without knowing what has and hasn't been published. When testing locally I branched from `main` and would have thought that this is the version the published version uses, but deployment is a total black box process to me and I have no idea how to actually check what's been published.

**Comment by ayya-vimala** [comment]
I cannot check anything at the moment but when I'm back in the monastery I will try locally and see which branch BN2 is running. Thanks for checking. This is very helpful!

**Comment by TrebuhD** [comment]
@ayya-vimala @aminahbl to the best of my recollection the live version is using the `148-text-view-reloads-first-page-over-and-over` branch. I'll try to make this somehow visible in the frontend!

**Comment by ayya-vimala** [comment]
This seems to have been resolved with latest update.
