### ISSUE TITLE
"selectedSegment" is not passed on to backend

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend-next#164]
How to reproduce: Call website with this url: https://buddhanexus2.kc-tbts.uni-hamburg.de/db/pli/an10/text?selectedSegment=an10%3A28.1.1&selectedSegmentIndex=0
Expected behavior: selectedSegment=an10%3A28.1.1 should get passed on to the backend as parameter "active_segment", but this is not happening at the moment, only 'none' is transmitted. Additionally, the frontend has to scroll the viewport to the active segment as the response only returns the page where the active segment can occur

**Comment by sebastian-nehrdich** [comment]
I have an update on this problem: It seems that the passing on is working ok when the result is on the first page/the text only has one page, like here: https://buddhanexus2.kc-tbts.uni-hamburg.de/db/skt/T06sthtvbhu/text?selectedSegment=T06sthtvbhu%3A19&selectedSegmentIndex=0
But it fails when we are on a different page: https://buddhanexus2.kc-tbts.uni-hamburg.de/en/db/skt/GSP33bhgsbh_u/text?selectedSegment=GSP33bhgsbh_u%3A4039&selectedSegmentIndex=0

**Comment by ayya-vimala** [comment]
Seems to be resolved in main branch.
